# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
  - id: 8453
    start_block: 0
    contracts:
      - name: VaultFactory
        address:
          - 0xEc9A1021cC0d4619ac6405a648239bEB0bFCf76C
        handler: src/EventHandlers.ts
        events:
          - event: AssetDeposited(address vaultAddress, bytes32 orderId)
          - event: CancelDeposit(address vaultAddress, bytes32 orderId)
          - event: OrderCancelled(address indexed vaultAddress, bytes32 indexed orderId)
          - event: OrderCreated(uint16 _platform, address _platformAddress, uint16 _parameter, uint32 destinationChainId, uint32 _salt, uint256 conditionValue, address vault, bytes32 orderId)
          - event: OrderExecuted(address indexed vaultAddress, bytes32 indexed orderId)
          - event: VaultCreated(address indexed vaultAddress, address indexed owner)
unordered_multichain_mode: true
field_selection:
  transaction_fields:
    - "hash"
